##################### default args #####################
common:
  cpu: 0 # action='store_true', help='use CPU instead of CUDA'
  task: completion # task

eval:
  path: ~/.ncc/py150/seqrnn_debug/checkpoints/checkpoint_last.pt # , metavar='FILE', help='path(s) to model file(s), colon separated'
  model_overrides: '{}' # default="{}", type=str, metavar='DICT', help='a dictionary used to override model args at generation '
  checkpoint_suffix: '' # default='', help='Suffix to add to the checkpoint file name'
  predict_type: 'leaf_id'

task:
  data: ~/.ncc/py150/seqrnn_debug/data-raw # /tmp/pycharm_project_629/data-bin help='colon separated path to data directories list, will be iterated upon during epochs in round-robin manner'
  source_lang: tok

distributed:
  device_id: 6 # '--local_rank', default=0, type=int, help='which GPU to use (usually configured automatically)'