##################### default args #####################
common:
  thread_num: 2 # （固定，不要调）load and process data with multi-process
  seed: 666 # （固定，不要调）init seed for numpy/torch/random/scipy and so on
  device:  7   # GPU device. if None, as CPU

  init_weights: ~  # None, xulu, xulu2, xulu3

  init_bound: 1e-1 # （固定，不要调）
  init_normal_std: 1e-4 # （固定，不要调）
  result_table_format: 'github' # （固定，不要调）latex (https://pypi.org/project/tabulate/)


dataset:
  # 100_small
  save_dir: '/data/sjd/d/p_d/fse20all/100_small/result'  # realdoctor
  dataset_dir: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/key/100_small' # realdoctor
  #dir: '/data/wy/ghproj_d/fse20all/100_small' # rtx
  #dataset_dir: '/data/wanyao/yang/ghproj_d/GitHub/datasetv2/key/100_small' # rtx

#  #  dataset_dir: '/data/wanyao/yang/ghproj_d/GitHub/datasetv2/key/200'
##  dataset_dir: '/data/wanyao/yang/ghproj_d/GitHub/datasetv2/key/100'
#  dataset_dir: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/key/100'
#
#  # save your model and eval files
#  # save_dir: 'C:\Users\GS65_2070mq\Documents\GitHub\naturalcodev2_save'
##  save_dir: '/data/wanyao/yang/ghproj_d/GitHub/naturalcodev2'
#  save_dir: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/result/summarization'
#  ##################### dataset and other args #####################
#  # dict files(tok, tree, path sbt, sbt2, code_tokens, docstring_tokens, method)
  # load from code_modalities

  tree_leaf_subtoken: True
  portion: 0.01         # 0.4 # train data portion, 0~1.0
  leaf_path_k: 30 #（固定，不要调）
  # if you need 2 or more than 2 languages to merge together before feeding networks, set it as True
  # generally used for transfer reinforcement learning (TRL)
  merge_xlng: False
  source:
    dataset_lng:
#      - 'python'
      - 'ruby'
#      - 'javascript'
#      - 'php'
#      - 'java'
#      - 'go'

    mode:
      - 'train'
      - 'valid'
      - 'test'

  target:
    ~


training:
  ##################### model args #####################
  #  summarization: tok, ast, path sbt, sbt2
  #  retrieval: code_tokens, docstring_tokens, method
  code_modalities:
#    - tok
    - ast
#    - path

  train_epoch: 50 # （固定，不要调）50已经足够，一般20-30epoch就基本收敛了
  batch_size: 128 # 128
  log_interval: 5 # （固定，不要调）write log info per log_interval iteration

  # network: encoder
  rnn_type: 'LSTM' # （固定，不要调）RNN type: 'GRU','LSTM', LSTM as default
  rnn_layer_num: 1 # （固定，不要调）RNN layer num
  rnn_hidden_size: 512 # （固定，不要调）RNN hidden size
  rnn_bidirectional: False    # （固定，不要调）
  embed_size: 300 # （固定，不要调）word-embedding size
  tree_lstm_cell_type: 'nary' # （固定，不要调）DGL tree LSTM cell, if nary -> TreeLSTMCell, else    -> ChildSumTreeLSTMCell
  code_modal_transform: False # （固定，不要调）False # code modalities transform with FCs
  conv2d_out_channels: 512 # （固定，不要调）
  conv2d_kernels: # （固定，不要调）
    - 2
    - 3
    - 4
    - 5

  # encoder RNN's output as decoder RNN's hidden_state(h, c)
  # 1) None, for zero_init as decoder RNN's hidden_state
  # 2) h, for only encoder RNN's output as decoder RNN's hidden_state(h)
  # 3) c, for only encoder RNN's output as decoder RNN's hidden_state(c)
  # 3) hc, for encoder RNN's output as decoder RNN's hidden_state(h, c)
  enc_hc2dec_hc: 'h' # （固定，不要调）'hc', 'h'

  # network: decoder
#  attn_type: dot # ~, general, dot, mlp, intra
  attn_type: ~ # ~, general, dot, mlp, intra
  attn_unit: 512 # （固定，不要调）
  self_attn_size: 50 # （固定，不要调）
#  intra_attn_eps: 1e-12
  pointer: False # pointer-generator, True, False
  max_predict_length: 65  # （固定，不要调）max generation length for decoder
  dropout: 0 # （固定，不要调）dropout
  decoder_input_feed: False # （固定，不要调）True, False

  # used to create the corresponding saved folder
  # ~, enc_hc2dec_hc, optim_AdamW, optim_Adagrad, optim_RMSprop, optim_SGD, decoder_input_feed_True
  # lr_0.01, lr_0.0001, lr_0.0004, lr_0.001_milestones1040,
  # max_grad_norm1.0, max_grad_norm10, max_grad_norm20, max_grad_norm100,
  # dropout_0.2, dropout_0.4, dropout_0.6, dropout_0.8,
  # rnn_layer_num_2, rnn_bidirectional_True
  # tok8path_lr_0.001, tok8path_lr_0.0001
  # tok8path_lr0.01_gamma0.1_milestones1040, tok8path_lr0.001_gamma0.5_milestones1040, tok8path_lr0.001_gamma0.5_milestones10203040,     tok8path_lr0.0004_gamma0.5_milestones2040, tok8path_lr0.0004_gamma0.5_milestones2040_code_modal_transformFalse
#  tok8path_lr0.001ep20-lr0.0004
#  attnDot, pointerTrue, tok8path_attnDot, tok8path_pointerTrue
  tuning: ~ # 这里的tuning是parameter tuning，我在这里加一个组合名字后，我的模型会存到相应的目录中，因为我们现在的model_name有点简单，容易重名字


# inference
testing:
  beam_size: 10
  max_predict_length: ~ # max generation length for decoder
  metrics:
    - 'bleu'
    - 'cider'
#    - 'rouge'
#    - 'meteor'

# supervised learning
sl:
  optim: 'Adam' # （固定，不要调）'Adam', 'AdamW', 'Adagrad', 'RMSprop', 'SGD'

# default
  lr: 4e-4 # 默认最优
  lr_gamma: 0.5 # （固定，不要调）0.1
  lr_milestones: # 默认最优，epochs when lr => lr * lr_gamma
    - 20 # 1e-4
    - 40 # 1e-5

  warmup_factor: 0.2 #（固定，不要调）
  warmup_epochs: -1 # （固定，不要调）-1: no warmup
  max_grad_norm: -1 # （固定，不要调）-1: no gradient clips  1.0, 10, 20, 100

# policy gradient
pg:
  optim: 'Adam'
  lr: 1e-4
  max_grad_norm: -1 # -1: no gradient clips  1.0
  reward_func: 'bleu'
  rl_weight: 1 # 0.8
#  lr_gamma: 0.1 # 0.1
#  lr_milestones: # epochs when lr => lr * lr_gamma
#    - 20 # 1e-4
#    - 40 # 1e-5
#  warmup_factor: 0.2
#  warmup_epochs: 1

# self-critical
sc:
  optim: 'Adam'
  lr: 1e-4
  max_grad_norm: -1 # -1: no gradient clips  1.0
  reward_func: 'bleu'
#  rl_weight: 0.8
  rl_weight: 1
