##################### default args #####################
common:
  thread_num: 3 # load and process data with multi-process
  seed: 666 # init seed for numpy/torch/random/scipy and so on
  device: 0 # GPU device. if None, as CPU

  init_weights: ~  # None，xulu， xulu2，xulu3

  init_bound: 1e-1
  init_normal_std: 1e-4
  result_table_format: 'github' # latex (https://pypi.org/project/tabulate/)

dataset:
  dataset_dir: '/data/wanyao/yang/ghproj_d/GitHub/datasetv2/key/100_small'
  # save your model and eval files
  save_dir: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/result/summarization'
  ##################### dataset and other args #####################
  # dict files(tok, tree, path sbt, sbt2, code_tokens, docstring_tokens, method)
  # load from code_modalities

  tree_leaf_subtoken: True
  portion: 0.0001 # only for evaluate meta-learner, using part data is quick
  leaf_path_k: 30
  source:
    dataset_lng:
      - 'python'
      - 'javascript'
      - 'php'
      - 'java'

    mode:
      - 'train'
      - 'valid'

  target:
    dataset_lng:
      - 'ruby'

    mode:
      - 'train'
      - 'valid'
      - 'test'


training:
  ##################### model args #####################
  #  summarization: tok, ast, path sbt, sbt2
  #  retrieval: code_tokens, docstring_tokens, method
  code_modalities:
    - tok
    - path

  train_epoch: 10000 # a large num, because maml is hard to train
  batch_size: 128
  log_interval: 5 # write log info per log_interval iteration

  # network: encoder
  rnn_type: 'LSTM' # RNN type: 'GRU','LSTM', LSTM as default
  rnn_layer_num: 1 # RNN layer num
  rnn_hidden_size: 512 # RNN hidden size
  rnn_bidirectional: True

  embed_size: 300 # word-embedding size
  embed_pooling: ~

  tree_lstm_cell_type: 'nary' # DGL tree LSTM cell, if nary -> TreeLSTMCell, else    -> ChildSumTreeLSTMCell
  code_modal_transform: True # code modalities transform with FCs
  conv2d_out_channels: 512
  conv2d_kernels:
    - 2
    - 3
    - 4
    - 5

  # encoder RNN's output as decoder RNN's hidden_state(h, c)
  # 1) None, for zero_init as decoder RNN's hidden_state
  # 2) h, for only encoder RNN's output as decoder RNN's hidden_state(h)
  # 3) c, for only encoder RNN's output as decoder RNN's hidden_state(c)
  # 3) hc, for encoder RNN's output as decoder RNN's hidden_state(h, c)
  enc_hc2dec_hc: 'h'

  # network: decoder
  attn_type: 'dot' # ~, general, dot, mlp, intra
  attn_unit: 512
  self_attn_size: 50
  intra_attn_eps: 1e-12
  pointer: True # pointer-generator
  max_predict_length: 65 # max generation length for decoder
  dropout: 0.2 # dropout
  decoder_input_feed: False # （固定，不要调）True, False


# inference
testing:
  beam_size: 10
  max_predict_length: ~ # max generation length for decoder

  metrics:
    - 'bleu'
    #    - 'meteor'
    #    - 'rouge'
    - 'cider'

# supervised learning
sl:
  optim: 'Adam'
  lr: 4e-4
  lr_gamma: 0.1 # 0.1
  lr_milestones: # epochs when lr => lr * lr_gamma
    - 20 # 4e-5
    - 40 # 4e-6
  warmup_factor: 0.2
  warmup_epochs: 1

  max_grad_norm: -1 # -1: no gradient clips  1.0


# meta learning
maml:
  meta_optim: 'SGD' # meta-optimizer
  meta_lr: 1e-3 # meta-learning rate
  max_grad_norm: 5

  meta_train_size: 10
  meta_val_size: 1

  mini_finetune_epoch: 10

# supervised learning
pg:
  optim: 'Adam'
  lr: 1e-4
  reward_func: 'bleu'

#  lr_gamma: 0.1 # 0.1
#  lr_milestones: # epochs when lr => lr * lr_gamma
#    - 20 # 1e-4
#    - 40 # 1e-5
#  warmup_factor: 0.2
#  warmup_epochs: 1

sc:
  optim: 'Adam'
  lr: 1e-4
  reward_func: 'bleu'

  lr_gamma: 0.1 # 0.1
  lr_milestones: # epochs when lr => lr * lr_gamma
    - 20 # 1e-4
    - 40 # 1e-5
  warmup_factor: 0.2
  warmup_epochs: 1

  max_grad_norm: -1 # -1: no gradient clips  1.0

  rl_weight: 1.0



ac:
  optim: 'Adam'
  optim_critic: 'Adam'
  lr: 1e-4
  lr_critic: 1e-4
  #  init_weights_critic: ~ # ~ None，xulu， xulu2，xulu3
  init_weights_critic: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/result/summarization/mm2seq/ruby/train_critic/critic-tok-bs128-lr0.001-attnNone-pointerFalse-ep50.pt'
  train_epoch_critic: 50
  train_epoch_ac: 50

gan:
  optim: 'Adam'
  optim_disc: 'Adam'
  lr: 1e-4
  lr_disc: 1e-4
  comment_fake_path: '/data/wanyao/yang/ghproj_d/GitHub/datasetv2/key/100/ruby/comment_fake'
  init_weights_disc: ~ # ~ None，xulu， xulu2，xulu3
  #  init_weights_disc: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/result/summarization/mm2seq/ruby/train_critic/critic-tok-bs128-lr0.001-attnNone-pointerFalse-ep50.pt'
  train_epoch_disc: 50
  train_epoch_gan: 50

arel:
  optim: 'Adam'
  optim_reward_model: 'Adam'
  lr: 1e-4
  lr_reward_model: 1e-4
  init_weights_reward_model: ~ # ~ None，xulu， xulu2，xulu3
  #  init_weights_reward_model: '/data/wanyao/ghproj_d/naturalcodev2/datasetv2/result/summarization/mm2seq/ruby/train_critic/critic-tok-bs128-lr0.001-attnNone-pointerFalse-ep50.pt'
  train_epoch_reward_model: 50
  train_epoch_arel: 50

  D_iter: 100
  G_iter: 100
  always: False
# fine tuning




dtrl:
  # if you need 2 or more than 2 languages to merge together before feeding networks, set it as True
  # generally used for depp transfer reinforcement learning (DTRL)
  merge_xlng: True

  optim: 'Adam'
  lr: 4e-4
  lr_gamma: 0.1 # 0.1
  lr_milestones: # epochs when lr => lr * lr_gamma
    - 20 # 1e-4
    - 40 # 1e-5
  warmup_factor: 0.2
  warmup_epochs: 1
  max_grad_norm: -1 # -1: no gradient clips  1.0

  reward_func: 'bleu'

kd:
  xxx: ~
