##################### default args #####################
common:
  cpu: 1 # action='store_true', help='use CPU instead of CUDA'
  task: retrieval # task

eval:
  path: ~/.ncc/CodeSearchNet/base/data-raw/_ruby/checkpoints/checkpoint_last.pt # , metavar='FILE', help='path(s) to model file(s), colon separated'
  model_overrides: '{}' # default="{}", type=str, metavar='DICT', help='a dictionary used to override model args at generation '
  checkpoint_suffix: '' # default='', help='Suffix to add to the checkpoint file name'
  predict_type: 'leaf_ids'

task:
  data: ~/.ncc/CodeSearchNet/base/data-raw/_ruby # /tmp/pycharm_project_629/data-bin help='colon separated path to data directories list, will be iterated upon during epochs in round-robin manner'
  source_lang: code_tokens
  target_lang: docstring_tokens

model:
  arch: nbow

dataset:
  joined_dictionary: 0

distributed:
  device_id: 0 # '--local_rank', default=0, type=int, help='which GPU to use (usually configured automatically)'