preprocess:
  task: retrieval # task', metavar='TASK', default="translation", choices=TASK_REGISTRY.keys(), help='task'
  source_lang: code_tokens
  target_lang: docstring_tokens
  only_source: 0
  trainpref: ~/.ncc/code_search_net/flatten/ruby/train #", metavar="FP", default=None, help="train file prefix"
  validpref: ~/.ncc/code_search_net/flatten/ruby/valid #", metavar="FP", default=None, help="comma separated, valid file prefixes"
  testpref:  ~/.ncc/code_search_net/flatten/ruby/test  #", metavar="FP", default=None, help="comma separated, test file prefixes"

  # bin dataset
  dataset_impl: mmap #', metavar='FORMAT', default='mmap', choices=get_available_dataset_impl(), help='output dataset implementation'
  destdir: ~/.ncc/code_search_net/retrieval/csn/data-mmap #", metavar="DIR", default="data-bin", help="destination dir"

#  align_suffix: ~ # ", metavar="FP", default=None, help="alignment file suffix"
  thresholdsrc: 10 #", metavar="N", default=0, type=int, help="map words appearing less than threshold times to unknown"
  srcdict: ~ # code_tokens
  tgtdict: ~ # query_tokens
  nwordssrc: 10000 #", metavar="N", default=-1, type=int, help="number of source words to retain"
  nwordstgt: 10000
  alignfile: ~ #", metavar="ALIGN", default=None, help="an alignment file (optional)"
  workers: 1 # ", metavar="N", default=1, type=int, help="number of parallel workers"